[package]
name = "ai-papers3"
version = "0.1.0"
edition = "2024"
resolver = "2"

[[bin]]
name = "ai-papers3"
harness = false

[profile.release]
opt-level = "s"

[profile.dev]
debug = true
opt-level = "z"

[features]
default = []
experimental = ["esp-idf-svc/experimental"]

[dependencies]
log = "0.4"
esp-idf-hal = "0.45"
esp-idf-svc = { version = "0.50", features = ["std", "experimental"] }
esp-idf-sys = { version = "0.36", features = ["binstart"] }
embedded-sdmmc = "0.9.0"
chrono = "0.4.44"
serde = { version = "1.0.228", features = ["derive"] }
serde_yaml = "0.9.34"
thiserror = "2.0.18"
miniz_oxide = { version = "0.8.9", default-features = false, features = ["with-alloc"] }
heapless = "0.8.0"
embedded-graphics = "0.8.2"
taffy = { version = "0.5", default-features = false, features = ["std", "taffy_tree", "flexbox"] }

[build-dependencies]
embuild = "0.33"

[[package.metadata.esp-idf-sys.extra_components]]
component_dirs = ["components"]

