#!/usr/bin/env python3
"""
font_to_rust.py — Generate a Rust source file with embedded bitmap font data.

Usage:
    python3 tools/font_to_rust.py \
        assets/fonts/Ubuntu-Regular.ttf 20 \
        src/fonts/ubuntu_regular_20.rs \
        UBUNTU_REGULAR_20

The output file defines:
    pub static UBUNTU_REGULAR_20: FontFace<'static> = FontFace { ... };

Character set: ASCII printable (U+0020–U+007E) + Cyrillic (U+0400–U+044F).
"""

import argparse
import math
import os
from pathlib import Path

from PIL import Image, ImageDraw, ImageFont


def build_codepoints():
    """ASCII printable + Cyrillic block (А-я + Ёё)."""
    codepoints = list(range(0x20, 0x7F))   # ASCII space..~
    codepoints += list(range(0x400, 0x450)) # Cyrillic Ѐ..п (includes А-Я, а-я, Ё, ё)
    return sorted(set(codepoints))


def render_glyph(font, codepoint, ascent, descent):
    """Render a single glyph; return dict with bitmap bytes and metrics."""
    char = chr(codepoint)
    canvas_w = int(font.getlength(char)) + font.size * 2
    canvas_h = ascent + descent + font.size
    canvas = Image.new("1", (max(canvas_w, 1), max(canvas_h, 1)), 0)
    draw = ImageDraw.Draw(canvas)
    try:
        draw.text((0, ascent), char, font=font, fill=1, anchor="ls")
    except TypeError:
        draw.text((0, 0), char, font=font, fill=1)

    x_advance = max(1, int(round(font.getlength(char))))
    bbox = canvas.getbbox()
    if bbox is None:
        return {
            "codepoint": codepoint,
            "width": 0, "height": 0,
            "x_offset": 0, "y_offset": 0,
            "x_advance": x_advance,
            "bitmap": [],
        }

    glyph_img = canvas.crop(bbox)
    w, h = glyph_img.size
    pixels = glyph_img.load()

    bytes_per_row = (w + 7) // 8
    bitmap = []
    for row in range(h):
        row_bytes = [0] * bytes_per_row
        for col in range(w):
            if pixels[col, row]:
                row_bytes[col // 8] |= 0x80 >> (col % 8)
        bitmap.extend(row_bytes)

    return {
        "codepoint": codepoint,
        "width": w, "height": h,
        "x_offset": bbox[0],
        "y_offset": bbox[1] - ascent,
        "x_advance": x_advance,
        "bitmap": bitmap,
    }


def generate_rust(ttf_path: str, size: int, output_path: str, const_name: str):
    font = ImageFont.truetype(ttf_path, size)
    ascent, descent = font.getmetrics()
    codepoints = build_codepoints()

    glyphs = []
    bitmap_data = []
    for cp in codepoints:
        g = render_glyph(font, cp, ascent, descent)
        g["bitmap_offset"] = len(bitmap_data)
        bitmap_data.extend(g["bitmap"])
        glyphs.append(g)

    line_height = ascent + descent + math.ceil(size * 0.2)

    os.makedirs(os.path.dirname(os.path.abspath(output_path)), exist_ok=True)
    with open(output_path, "w", encoding="utf-8") as f:
        f.write("// AUTO-GENERATED by tools/font_to_rust.py — DO NOT EDIT\n")
        f.write("// Source: {} size={}\n\n".format(os.path.basename(ttf_path), size))
        f.write("use crate::fonts::FontFace;\nuse crate::fonts::GlyphInfo;\n\n")

        # ── bitmap ──────────────────────────────────────────────────────────────
        f.write(f"static BITMAP: &[u8] = &[\n")
        for i, byte in enumerate(bitmap_data):
            if i % 16 == 0:
                f.write("    ")
            f.write(f"0x{byte:02X},")
            if i % 16 == 15:
                f.write("\n")
            else:
                f.write(" ")
        if bitmap_data and len(bitmap_data) % 16 != 0:
            f.write("\n")
        f.write("];\n\n")

        # ── glyphs ───────────────────────────────────────────────────────────────
        f.write(f"static GLYPHS: &[GlyphInfo] = &[\n")
        for g in glyphs:
            line = (
                f"    GlyphInfo {{ codepoint: 0x{g['codepoint']:04X}, "
                f"width: {g['width']}, height: {g['height']}, "
                f"x_offset: {g['x_offset']}, y_offset: {g['y_offset']}, "
                f"x_advance: {g['x_advance']}, bitmap_offset: {g['bitmap_offset']} }},\n"
            )
            f.write(line)
        f.write("];\n\n")

        # ── FontFace constant ────────────────────────────────────────────────────
        f.write(f"pub static {const_name}: FontFace<'static> = FontFace {{\n")
        f.write(f"    size: {size},\n")
        f.write(f"    ascent: {ascent},\n")
        f.write(f"    descent: {descent},\n")
        f.write(f"    line_height: {line_height},\n")
        f.write(f"    glyphs: GLYPHS,\n")
        f.write(f"    bitmap: BITMAP,\n")
        f.write("};\n")

    print(f"Written {output_path}  ({len(bitmap_data)} bitmap bytes, {len(glyphs)} glyphs)")


def main():
    parser = argparse.ArgumentParser(description="Generate Rust bitmap font from TTF.")
    parser.add_argument("ttf_path",     help="Path to TTF font file")
    parser.add_argument("size",  type=int, help="Font size in points (pixels)")
    parser.add_argument("output_path",  help="Path to output .rs file")
    parser.add_argument("const_name",   help="Name for the generated FontFace constant")
    args = parser.parse_args()

    if not Path(args.ttf_path).exists():
        raise SystemExit(f"Font not found: {args.ttf_path}")

    generate_rust(args.ttf_path, args.size, args.output_path, args.const_name)


if __name__ == "__main__":
    main()
